version: '3.11'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
